"""update stat and athlete relationship for foreign key on athlete delete

Revision ID: 1c353ab3181a
Revises: 2ec6506e42fb
Create Date: 2026-06-12 13:59:06.697839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c353ab3181a'
down_revision: Union[str, Sequence[str], None] = '2ec6506e42fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('stats_athlete_id_fkey'), 'stats', type_='foreignkey')
    op.create_foreign_key(None, 'stats', 'athletes', ['athlete_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stats', type_='foreignkey')
    op.create_foreign_key(op.f('stats_athlete_id_fkey'), 'stats', 'athletes', ['athlete_id'], ['id'])
    # ### end Alembic commands ###
