"""Update Stat model to modern

Revision ID: 2ec6506e42fb
Revises: ffcfe44e9c20
Create Date: 2026-06-10 15:32:01.915881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ec6506e42fb'
down_revision: Union[str, Sequence[str], None] = 'ffcfe44e9c20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stats', 'attack_kills',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('stats', 'attack_errors',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('stats', 'attack_total',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('stats', 'attack_percentage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('stats', 'setting_assists',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('stats', 'setting_errors',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('stats', 'setting_attempts',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('stats', 'serving_rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('stats', 'serving_rating_total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('stats', 'serving_aces',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('stats', 'serving_errors',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('stats', 'serving_attempts',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('stats', 'serving_percentage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('stats', 'receiving_rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('stats', 'receiving_rating_total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('stats', 'receiving_errors',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('stats', 'receiving_attempts',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('stats', 'defense_digs',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('stats', 'defense_rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('stats', 'defense_rating_total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('stats', 'defense_errors',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('stats', 'defense_attempts',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('stats', 'blocking_total',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('stats', 'blocking_kills',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('stats', 'blocking_solos',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('stats', 'blocking_good_touches',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('stats', 'blocking_attempts',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('stats', 'blocking_errors',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_stats_id'), table_name='stats')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_stats_id'), 'stats', ['id'], unique=False)
    op.alter_column('stats', 'blocking_errors',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('stats', 'blocking_attempts',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('stats', 'blocking_good_touches',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('stats', 'blocking_solos',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('stats', 'blocking_kills',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('stats', 'blocking_total',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('stats', 'defense_attempts',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('stats', 'defense_errors',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('stats', 'defense_rating_total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('stats', 'defense_rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('stats', 'defense_digs',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('stats', 'receiving_attempts',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('stats', 'receiving_errors',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('stats', 'receiving_rating_total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('stats', 'receiving_rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('stats', 'serving_percentage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('stats', 'serving_attempts',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('stats', 'serving_errors',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('stats', 'serving_aces',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('stats', 'serving_rating_total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('stats', 'serving_rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('stats', 'setting_attempts',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('stats', 'setting_errors',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('stats', 'setting_assists',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('stats', 'attack_percentage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('stats', 'attack_total',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('stats', 'attack_errors',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('stats', 'attack_kills',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
