name: Test Project

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start PostgreSQL
        run: |
          cd server-py/tests 
          docker compose -f docker-compose.test.yml up -d

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.6"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: |
          cd server-py
          venv\scripts\activate
          pytest

      - name: Stop PostgreSQL
        if: always()
        run: docker compose -f docker-compose.test.yml down
